<a href="https://colab.research.google.com/github/Tejas-Bajaj/Intro-to-ml-dl/blob/main/Solution_of_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy 

In [ ]:
import numpy as np 


In [ ]:
# create a matrix 3x3 with values ranging from 50,58
#dont write code in this block
#ideal output is 


array([[50, 51, 52],
       [53, 54, 55],
       [56, 57, 58]])

In [ ]:
#write code here
a = np.array(range(50,59))
a = a.reshape(3,3)
a

array([[50, 51, 52],
       [53, 54, 55],
       [56, 57, 58]])

In [ ]:
# try recreating following array; If need some hint pm :)
#dont run this cell

array([[ 0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,
         2.5 ],
       [ 2.75,  3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,
         5.  ],
       [ 5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,
         7.5 ],
       [ 7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,  9.75,
        10.  ]])

In [ ]:
#write your code here . 
a = np.array(range(1,41))
a = a/4
mat = a.reshape(4,10)
mat

array([[ 0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,
         2.5 ],
       [ 2.75,  3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,
         5.  ],
       [ 5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,
         7.5 ],
       [ 7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,  9.75,
        10.  ]])

suppose you store above array into a variable named `mat`, 
and you are asked to perform slicing operations to get sub parts of the `mat` 

In [ ]:
# using slicing operation return this array
#dont write your code here

array([[3.5 , 3.75, 4.  ],
       [6.  , 6.25, 6.5 ]])

In [ ]:
#write code here
mat[1:3,3:6]

array([[3.5 , 3.75, 4.  ],
       [6.  , 6.25, 6.5 ]])

In [ ]:
#use different numpy operations on `mat` to get following output
#dont write code in this block



array([[0.75, 3.25, 5.75, 8.25],
       [1.  , 3.5 , 6.  , 8.5 ],
       [1.25, 3.75, 6.25, 8.75],
       [1.5 , 4.  , 6.5 , 9.  ],
       [1.75, 4.25, 6.75, 9.25]])

In [ ]:
a = mat[:,2:7].transpose()
a

array([[0.75, 3.25, 5.75, 8.25],
       [1.  , 3.5 , 6.  , 8.5 ],
       [1.25, 3.75, 6.25, 8.75],
       [1.5 , 4.  , 6.5 , 9.  ],
       [1.75, 4.25, 6.75, 9.25]])

In [ ]:
#use different numpy operations on `mat` to get following output
#dont write code in this block



array([0.75, 3.25, 5.75, 8.25])

In [ ]:
#write your code here. 
a = mat[:,2:7].transpose()
a[0,:]

array([0.75, 3.25, 5.75, 8.25])

In [ ]:
#use different numpy operations on `mat` to get following output
#dont write code in this block
#note that there is difference between above question and this question, In above question shape of the output array is (4,) and in this block, shape of output is (1,4)


array([[0.75, 3.25, 5.75, 8.25]])

In [ ]:
a = mat[:,2:7].transpose()
b = a[0,:]
# print(b.shape)
b = np.expand_dims(b,0)
# print(b.shape)
b

array([[0.75, 3.25, 5.75, 8.25]])

In [ ]:
mat

array([[ 0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,
         2.5 ],
       [ 2.75,  3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,
         5.  ],
       [ 5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,
         7.5 ],
       [ 7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,  9.75,
        10.  ]])

In [ ]:
#whats the sum of all elements in `mat`, 
sum_all = 
sum_row = 
sum_column = 
print("sum of all elements in `mat` :", sum_all)
print("sum across rows in `mat` :", sum_row)
print("sum across columns in `mat` :", sum_column)

sum of all elements in `mat` : 205.0
sum across rows in `mat` : [13.75 38.75 63.75 88.75]
sum across columns in `mat` : [16. 17. 18. 19. 20. 21. 22. 23. 24. 25.]


In [ ]:
sum_all = np.sum(mat, axis=None)
sum_row = np.sum(mat, axis=1)
sum_column = np.sum(mat, axis=0)
print("sum of all elements in `mat` :", sum_all)
print("sum across rows in `mat` :", sum_row)
print("sum across columns in `mat` :", sum_column)

sum of all elements in `mat` : 205.0
sum across rows in `mat` : [13.75 38.75 63.75 88.75]
sum across columns in `mat` : [16. 17. 18. 19. 20. 21. 22. 23. 24. 25.]


In [ ]:
# whats the standard deviation of all values in mat? 
std_mat = 
print("std of mat is : ", std_mat)

std of mat is :  2.885849095153799


In [ ]:
std_mat = np.std(mat)
print("std of mat is : ", std_mat)

std of mat is :  2.885849095153799


#pandas

In [1]:
!wget https://raw.githubusercontent.com/abhi-glitchhg/Intro-to-ml-dl/main/Week2/Assignment%202/data.csv

--2022-05-22 17:26:06--  https://raw.githubusercontent.com/abhi-glitchhg/Intro-to-ml-dl/main/Week2/Assignment%202/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2243759 (2.1M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   2.14M  --.-KB/s    in 0.07s   

2022-05-22 17:26:07 (32.2 MB/s) - ‘data.csv’ saved [2243759/2243759]



In [2]:
import pandas as pd

In [3]:
dataframe = pd.read_csv("data.csv")

In [ ]:
dataframe

Unnamed: 0 InvoiceNo StockCode                          Description  \
0               0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER   
1               1    536365     71053                  WHITE METAL LANTERN   
2               2    536365    84406B       CREAM CUPID HEARTS COAT HANGER   
3               3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE   
4               4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.   
...           ...       ...       ...                                  ...   
25010       25010    538351     22149           FELTCRAFT 6 FLOWER FRIENDS   
25011       25011    538351     22150             3 STRIPEY MICE FELTCRAFT   
25012       25012    538351     22174                           PHOTO CUBE   
25013       25013    538351     22326  ROUND SNACK BOXES SET OF4 WOODLAND    
25014       25014    538351     22327    ROUND SNACK BOXES SET OF 4 SKULLS   

       Quantity       InvoiceDate  UnitPrice  CustomerID         Country  
0             6    12/1/2010 8:26       2.55     17850.0  United Kingdom  
1             6    12/1/2010 8:26       3.39     17850.0  United Kingdom  
2             8    12/1/2010 8:26       2.75     17850.0  United Kingdom  
3             6    12/1/2010 8:26       3.39     17850.0  United Kingdom  
4             6    12/1/2010 8:26       3.39     17850.0  United Kingdom  
...         ...               ...        ...         ...             ...  
25010        23  12/10/2010 15:17       5.06         NaN  United Kingdom  
25011         1  12/10/2010 15:17       5.06         NaN  United Kingdom  
25012         4  12/10/2010 15:17       4.21         NaN  United Kingdom  
25013         1  12/10/2010 15:17       6.77         NaN  United Kingdom  
25014         2  12/10/2010 15:17       6.77         NaN         United   

[25015 rows x 9 columns]

In [ ]:
# check if there are any null values; print columnwise number of null values, and its percentage

In [ ]:
series1 = dataframe.isnull().sum()
series2 = series1*100/len(dataframe)
print("Number of null values in given dataframe: ", '\n', series1, '\n')
print("Percentage of null values in given dataframe: ", '\n', series2, '\n')

Number of null values in given dataframe:  
 Unnamed: 0        0
InvoiceNo         0
StockCode         0
Description     111
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     8959
Country           0
dtype: int64 

Percentage of null values in given dataframe:  
 Unnamed: 0      0.000000
InvoiceNo       0.000000
StockCode       0.000000
Description     0.443734
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     35.814511
Country         0.000000
dtype: float64 



In [ ]:
# how would you handle this null data points? - write in short..


In [ ]:
#write here.
'''
There are multiple ways in which NaN values can be handles:
1) Remove entries with null values - However there are many null values and doing this will reduce the data
2) Fill all NaN places with a specified value
3) Interpolation
4) Using measures of central tendency - Mean/Median for numbers and Mode for string data
'''


In [ ]:
# print list of all different countries and number of times it appeared in `Country` column  ; Also plot a count plot for `Country` column.


United Kingdom     23709
Germany              309
France               287
EIRE                 228
Norway               147
Portugal              94
Spain                 45
Lithuania             35
Iceland               31
Italy                 25
Australia             22
Denmark               20
Channel Islands       17
Japan                 17
Belgium               12
Poland                 8
Switzerland            6
Netherlands            2
United                 1
Name: Country, dtype: int64

In [4]:
country_count = dataframe["Country"].value_counts()
country_count

United Kingdom     23709
Germany              309
France               287
EIRE                 228
Norway               147
Portugal              94
Spain                 45
Lithuania             35
Iceland               31
Italy                 25
Australia             22
Denmark               20
Channel Islands       17
Japan                 17
Belgium               12
Poland                 8
Switzerland            6
Netherlands            2
United                 1
Name: Country, dtype: int64

In [5]:
#write code here for plotting.
#write code here for plotting.
import seaborn as sns
import matplotlib.pyplot as plt
vals = country_count.values
nos = country_count.index
# print(vals)
# print(nos)
sns.countplot(data = [vals, nos])


# Could not use this

ValueError: ignored

In [ ]:
#dataframe where country value correspond to "United Kingdom" 
#dont run this cell
british_dataframe 

InvoiceNo StockCode                          Description  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER       6.0   
1        536365     71053                  WHITE METAL LANTERN       6.0   
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER       8.0   
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE       6.0   
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.       6.0   
...         ...       ...                                  ...       ...   
12456    537381     22865               HAND WARMER OWL DESIGN      10.0   
12457    537381     22632            HAND WARMER RED RETROSPOT      24.0   
12458    537381     22633               HAND WARMER UNION JACK      20.0   
12459    537381     22867              HAND WARMER BIRD DESIGN      24.0   
12460    537381     22601       CHRISTMAS RETROSPOT ANGEL WOOD      17.0   

           InvoiceDate  UnitPrice  CustomerID         Country  
0       12/1/2010 8:26       2.55     17850.0  United Kingdom  
1       12/1/2010 8:26       3.39     17850.0  United Kingdom  
2       12/1/2010 8:26       2.75     17850.0  United Kingdom  
3       12/1/2010 8:26       3.39     17850.0  United Kingdom  
4       12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                ...        ...         ...             ...  
12456  12/6/2010 13:13       2.10     14667.0  United Kingdom  
12457  12/6/2010 13:13       2.10     14667.0  United Kingdom  
12458  12/6/2010 13:13       2.10     14667.0  United Kingdom  
12459  12/6/2010 13:13       2.10     14667.0  United Kingdom  
12460  12/6/2010 13:13       0.85     14667.0  United Kingdom  

[11806 rows x 8 columns]

In [6]:
british_dataframe = dataframe[dataframe['Country'] == "United Kingdom"]
british_dataframe

Unnamed: 0 InvoiceNo StockCode                          Description  \
0               0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER   
1               1    536365     71053                  WHITE METAL LANTERN   
2               2    536365    84406B       CREAM CUPID HEARTS COAT HANGER   
3               3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE   
4               4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.   
...           ...       ...       ...                                  ...   
25009       25009    538351     22147           FELTCRAFT BUTTERFLY HEARTS   
25010       25010    538351     22149           FELTCRAFT 6 FLOWER FRIENDS   
25011       25011    538351     22150             3 STRIPEY MICE FELTCRAFT   
25012       25012    538351     22174                           PHOTO CUBE   
25013       25013    538351     22326  ROUND SNACK BOXES SET OF4 WOODLAND    

       Quantity       InvoiceDate  UnitPrice  CustomerID         Country  
0             6    12/1/2010 8:26       2.55     17850.0  United Kingdom  
1             6    12/1/2010 8:26       3.39     17850.0  United Kingdom  
2             8    12/1/2010 8:26       2.75     17850.0  United Kingdom  
3             6    12/1/2010 8:26       3.39     17850.0  United Kingdom  
4             6    12/1/2010 8:26       3.39     17850.0  United Kingdom  
...         ...               ...        ...         ...             ...  
25009         6  12/10/2010 15:17       4.21         NaN  United Kingdom  
25010        23  12/10/2010 15:17       5.06         NaN  United Kingdom  
25011         1  12/10/2010 15:17       5.06         NaN  United Kingdom  
25012         4  12/10/2010 15:17       4.21         NaN  United Kingdom  
25013         1  12/10/2010 15:17       6.77         NaN  United Kingdom  

[23709 rows x 9 columns]

In [ ]:
# now as every entry in "country" column of british_dataframe is same ("United Kingdom"); we can just remove the column 
#as it is not providing much information to us

In [ ]:
#drop country column of `british_dataframe`

In [7]:
british_dataframe = british_dataframe.drop("Country", axis = 1)
british_dataframe

Unnamed: 0 InvoiceNo StockCode                          Description  \
0               0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER   
1               1    536365     71053                  WHITE METAL LANTERN   
2               2    536365    84406B       CREAM CUPID HEARTS COAT HANGER   
3               3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE   
4               4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.   
...           ...       ...       ...                                  ...   
25009       25009    538351     22147           FELTCRAFT BUTTERFLY HEARTS   
25010       25010    538351     22149           FELTCRAFT 6 FLOWER FRIENDS   
25011       25011    538351     22150             3 STRIPEY MICE FELTCRAFT   
25012       25012    538351     22174                           PHOTO CUBE   
25013       25013    538351     22326  ROUND SNACK BOXES SET OF4 WOODLAND    

       Quantity       InvoiceDate  UnitPrice  CustomerID  
0             6    12/1/2010 8:26       2.55     17850.0  
1             6    12/1/2010 8:26       3.39     17850.0  
2             8    12/1/2010 8:26       2.75     17850.0  
3             6    12/1/2010 8:26       3.39     17850.0  
4             6    12/1/2010 8:26       3.39     17850.0  
...         ...               ...        ...         ...  
25009         6  12/10/2010 15:17       4.21         NaN  
25010        23  12/10/2010 15:17       5.06         NaN  
25011         1  12/10/2010 15:17       5.06         NaN  
25012         4  12/10/2010 15:17       4.21         NaN  
25013         1  12/10/2010 15:17       6.77         NaN  

[23709 rows x 8 columns]

In [ ]:
#Now make dataframe containing countries other than UK, name the dataframe as non_british_dataframe

In [8]:
non_british_dataframe = dataframe[dataframe['Country'] != "United Kingdom"]
non_british_dataframe

Unnamed: 0 InvoiceNo StockCode                        Description  \
26             26    536370     22728          ALARM CLOCK BAKELIKE PINK   
27             27    536370     22727          ALARM CLOCK BAKELIKE RED    
28             28    536370     22726         ALARM CLOCK BAKELIKE GREEN   
29             29    536370     21724    PANDA AND BUNNIES STICKER SHEET   
30             30    536370     21883                   STARS GIFT TAPE    
...           ...       ...       ...                                ...   
24046       24046    538311    85099B            JUMBO BAG RED RETROSPOT   
24047       24047    538311     22665  RECIPE BOX BLUE SKETCHBOOK DESIGN   
24048       24048    538311     22847        BREAD BIN DINER STYLE IVORY   
24049       24049    538311      POST                            POSTAGE   
25014       25014    538351     22327  ROUND SNACK BOXES SET OF 4 SKULLS   

       Quantity       InvoiceDate  UnitPrice  CustomerID   Country  
26           24    12/1/2010 8:45       3.75     12583.0    France  
27           24    12/1/2010 8:45       3.75     12583.0    France  
28           12    12/1/2010 8:45       3.75     12583.0    France  
29           12    12/1/2010 8:45       0.85     12583.0    France  
30           24    12/1/2010 8:45       0.65     12583.0    France  
...         ...               ...        ...         ...       ...  
24046        10  12/10/2010 13:48       1.95     12785.0  Portugal  
24047         6  12/10/2010 13:48       2.95     12785.0  Portugal  
24048         1  12/10/2010 13:48      16.95     12785.0  Portugal  
24049         2  12/10/2010 13:48      28.00     12785.0  Portugal  
25014         2  12/10/2010 15:17       6.77         NaN   United   

[1306 rows x 9 columns]

In [ ]:
#remove the row which has null entry in `Country` Column; 
#dont remove the rows which have null values in column other than `Country`


In [9]:
#write code here. 
dataframe.dropna(subset=["Country"])
dataframe

# Apparently the given data does not have any such entry with NaN country...

Unnamed: 0 InvoiceNo StockCode                          Description  \
0               0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER   
1               1    536365     71053                  WHITE METAL LANTERN   
2               2    536365    84406B       CREAM CUPID HEARTS COAT HANGER   
3               3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE   
4               4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.   
...           ...       ...       ...                                  ...   
25010       25010    538351     22149           FELTCRAFT 6 FLOWER FRIENDS   
25011       25011    538351     22150             3 STRIPEY MICE FELTCRAFT   
25012       25012    538351     22174                           PHOTO CUBE   
25013       25013    538351     22326  ROUND SNACK BOXES SET OF4 WOODLAND    
25014       25014    538351     22327    ROUND SNACK BOXES SET OF 4 SKULLS   

       Quantity       InvoiceDate  UnitPrice  CustomerID         Country  
0             6    12/1/2010 8:26       2.55     17850.0  United Kingdom  
1             6    12/1/2010 8:26       3.39     17850.0  United Kingdom  
2             8    12/1/2010 8:26       2.75     17850.0  United Kingdom  
3             6    12/1/2010 8:26       3.39     17850.0  United Kingdom  
4             6    12/1/2010 8:26       3.39     17850.0  United Kingdom  
...         ...               ...        ...         ...             ...  
25010        23  12/10/2010 15:17       5.06         NaN  United Kingdom  
25011         1  12/10/2010 15:17       5.06         NaN  United Kingdom  
25012         4  12/10/2010 15:17       4.21         NaN  United Kingdom  
25013         1  12/10/2010 15:17       6.77         NaN  United Kingdom  
25014         2  12/10/2010 15:17       6.77         NaN         United   

[25015 rows x 9 columns]

In [ ]:

#now we want you to sort the dataframe acccording to the "UnitPrice" column; sorting should be descending
#if there is a tie/ same value use quantity as tie-braker. 


In [10]:
dataframe.sort_values(by=['UnitPrice', 'Quantity'], ascending = False)

Unnamed: 0 InvoiceNo  StockCode Description  Quantity      InvoiceDate  \
15017       15017    537632  AMAZONFEE  AMAZON FEE         1  12/7/2010 15:08   
15016       15016   C537630  AMAZONFEE  AMAZON FEE        -1  12/7/2010 15:04   
16356       16356   C537651  AMAZONFEE  AMAZON FEE        -1  12/7/2010 15:49   
16232       16232   C537644  AMAZONFEE  AMAZON FEE        -1  12/7/2010 15:34   
16357       16357   C537652  AMAZONFEE  AMAZON FEE        -1  12/7/2010 15:51   
...           ...       ...        ...         ...       ...              ...   
20506       20506    538058      20966         NaN      -150  12/9/2010 13:38   
21520       21520    538092      37467         NaN      -177  12/9/2010 14:49   
19996       19996    537999      22034         NaN      -223  12/9/2010 11:44   
7292         7292    537028      21696         NaN      -320  12/3/2010 16:36   
21518       21518    538090      20956           ?      -723  12/9/2010 14:48   

       UnitPrice  CustomerID         Country  
15017   13541.33         NaN  United Kingdom  
15016   13541.33         NaN  United Kingdom  
16356   13541.33         NaN  United Kingdom  
16232   13474.79         NaN  United Kingdom  
16357    6706.71         NaN  United Kingdom  
...          ...         ...             ...  
20506       0.00         NaN  United Kingdom  
21520       0.00         NaN  United Kingdom  
19996       0.00         NaN  United Kingdom  
7292        0.00         NaN  United Kingdom  
21518       0.00         NaN  United Kingdom  

[25015 rows x 9 columns]

In [ ]:
# find the mean, maximum and minimum  of unit price based on country ; hint - use `groupby` operation
